name: Temp file

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    environment: Dev
    steps:
      - run: |
          echo ${{ secrets.DEVSECRETKEY }} >> api.txt
          cat api.txt
        
